import Head from 'next/head';
import { Session } from 'next-auth';
import { HotJar } from '../hotjar';
import { CookieConsent } from '../cookieConsent';
import { Header } from './header/header';
import { Footer } from './footer';
import { ProviderLayout } from './providerLayout';

const metadata = {
  title: 'Tach RA Demo',
  description: 'Generated by tachignite-web-ra',
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: '48x48' },
      { url: '/favicon.svg', sizes: 'any', type: 'image/svg+xml' },
    ],
    apple: {
      url: '/apple-touch-icon.png',
    },
    other: [
      {
        rel: 'manifest',
        url: '/site.webmanifest',
      },
    ],
  },
};

export type RootLayoutProps = {
  session: Session;
  children: React.ReactNode;
};

export function RootLayout({ session, children }: RootLayoutProps) {
  return (
    <ProviderLayout session={session}>
      <div className="dark:bg-tachDark bg-white dark:text-white text-tachDark min-h-screen flex flex-col">
        <Head>
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />
          <link rel="icon" href="/favicon.ico" />
          <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
          <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
          <link rel="manifest" href="/site.webmanifest" />
        </Head>
        <Header />
        <div className="flex-grow">{children}</div>
        <div>
          <Footer />
          <CookieConsent />
          <HotJar />
        </div>
      </div>
    </ProviderLayout>
  );
}
